### ISSUE TITLE
Highscore: Can't re-upload old Highscore with new flag

### ISSUE THREAD

**Issue by tolik518** [evanbowman/skyland-sever#1]
Reuoloading the Highscore with 2023.3.31.0 Version leads to an error:
![Screenshot_20230401_172632](https://user-images.githubusercontent.com/3026792/229298435-2175a436-9312-4442-93dd-d426fdd959d9.jpg)

**Comment by evanbowman** [comment]
This is expected actually, I'll need to create a better error page. But the webserver basically isn't letting you upload something because an identical entry already exists. I guess I could make a flag image icon part of the primary key... just a minute

**Comment by evanbowman** [comment]
Ok, I changed the uniqueness constraint.

**Comment by tolik518** [comment]
Ok, so it won't update my old entry but create a new entry?

**Comment by evanbowman** [comment]
The database is not designed to support modifications, because the website has no user accounts. Someone other than the uploader could modify entries. For this special case of a newly added flag parameter, I'll resolve the duplicates manually

**Comment by evanbowman** [comment]
I fixed the duplicate entry, do you want you new flag retroactively applied to your previous uploads?

**Comment by tolik518** [comment]
> I fixed the duplicate entry, do you want you new flag retroactively applied to your previous uploads?

If you'd be so kind, of course :)

It would be also nice if it could show transparency as transparent intead of pink

**Comment by evanbowman** [comment]
ohh, I know what happened here, 0xff00ff is the transparency color in the gba game, I'll change it to display as a transparent color. I sort of just copy-pasted the palette table and didn't think about transparency

**Comment by evanbowman** [comment]
Fixed! The old flag images may still appear for a bit though due to browser image cache.
